package config

const (
	EnvAppEnvironment        = "APP_ENV"
	EnvPort                  = "PORT"
	EnvDataStore             = "DATA_STORE"
	EnvDatabaseURL           = "DATABASE_URL"
	EnvDatabaseMaxConns      = "DATABASE_MAX_CONNS"
	EnvAuthProvider          = "AUTH_PROVIDER"
	EnvClerkIssuer           = "CLERK_ISSUER"
	EnvClerkJWKSURL          = "CLERK_JWKS_URL"
	EnvClerkAudience         = "CLERK_AUDIENCE"
	EnvClerkSecretKey        = "CLERK_SECRET_KEY"
	EnvAllowedOrigins        = "ALLOWED_ORIGINS"
	EnvResendAPIKey          = "RESEND_API_KEY"
	EnvResendFromEmail       = "RESEND_FROM_EMAIL"
	EnvResendReplyToEmail    = "RESEND_REPLY_TO_EMAIL"
	EnvClerkWebhookSecret    = "CLERK_WEBHOOK_SECRET"
	EnvR2AccountID           = "R2_ACCOUNT_ID"
	EnvR2AccessKeyID         = "R2_ACCESS_KEY_ID"
	EnvR2SecretAccessKey     = "R2_SECRET_ACCESS_KEY"
	EnvR2Bucket              = "R2_BUCKET"
	EnvR2PublicURL           = "R2_PUBLIC_URL"
	EnvFCMServiceAccountJSON = "FCM_SERVICE_ACCOUNT_JSON"
	EnvOheyAdminEmails       = "OHEY_ADMIN_EMAILS"
	EnvOriginVerifySecret    = "ORIGIN_VERIFY_SECRET"
)
